# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ws2bVBTLVRie4MJBbeb0tG1LLR7zONT2
"""

import numpy as np
import pandas as pd

# Create fake data (simulating 10 days of pump data, every 10 minutes)
np.random.seed(42)
time = pd.date_range(start='2026-01-01', periods=1440, freq='10min')

# Flow_m3h is the volumetric flow rate (m3 per hour) through the meter,
# NOT a total volume — it's a rate, measured fresh at every timestamp.
flow = np.random.normal(100, 5, 1440)  # Flow around 100 m3/h
pressure = 50 + (flow * 0.5) + np.random.normal(0, 2, 1440)  # Pressure depends on flow
temperature = 40 + (flow * 0.15) + np.random.normal(0, 1, 1440)  # Temperature depends on flow

# Inject a GRADUAL fault (realistic degradation, not a sudden cliff-edge drop)
fault_start, fault_end = 600, 800
pressure[fault_start:fault_end] += np.linspace(0, -15, fault_end - fault_start)
temperature[fault_start:fault_end] += np.linspace(0, 4, fault_end - fault_start)  # temp creeps up as pressure drops

# PVT effect: as pressure drops, the fluid expands, increasing the volumetric flow rate (m3/h) through the meter.
flow[fault_start:fault_end] += np.linspace(0, 3, fault_end - fault_start)

data = pd.DataFrame({
    'Timestamp': time,
    'Flow_m3h': flow,
    'Pressure_bar': pressure,
    'Temperature_C': temperature
})
data.to_csv('pump_data.csv', index=False)
print("Synthetic subsea pump data created with realistic PVT-coupled degradation (Pressure drops, Flow drifts up, Temperature rises).")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


class SubseaMonitor:
    """Condition-monitoring pipeline for simulated subsea pump sensor data.

    Loads pressure/flow/temperature readings, detects performance
    anomalies, computes a combined health score, generates a root-cause
    hypothesis report, and builds a 4-panel monitoring dashboard.

    Engineering thresholds used throughout (rolling window, Z-score cutoff,
    root-cause deltas) are simplified, illustrative values chosen to make
    the demo behave sensibly on synthetic data — not values calibrated
    against real OneSubsea equipment. In a production setting these would
    be tuned against historical failure data and equipment specifications.
    """

    def __init__(self, rolling_window=50, anomaly_z=2.5, health_alert_threshold=2.0):
        """Initializes the monitor with its detection thresholds.

        Args:
            rolling_window: Number of readings used to define the local
                "normal" baseline for anomaly detection. Data is sampled
                every 10 minutes, so 50 readings is roughly 8 hours —
                long enough to smooth out sensor noise, short enough to
                still react within a single operating shift.
            anomaly_z: Number of rolling standard deviations a pressure
                reading must deviate from its rolling mean to be flagged
                as a performance deviation. 2.5 is a common statistical
                convention balancing false alarms against missed events.
            health_alert_threshold: Composite health score above which the
                system is flagged with a System_Alert. A value of 2.0
                means Pressure/Flow/Temperature are, on average, 2
                standard deviations from their normal operating range.
        """
        self.rolling_window = rolling_window
        self.anomaly_z = anomaly_z
        self.health_alert_threshold = health_alert_threshold
        self.df = None
        self.events = None

    def load_data(self, filepath):
        """Loads sensor data from CSV and parses the timestamp column.

        Args:
            filepath: Path to the CSV produced by create_data.py, containing
                Timestamp, Flow_m3h, Pressure_bar and Temperature_C columns.

        Returns:
            self, so calls can be chained.
        """
        self.df = pd.read_csv(filepath)
        self.df['Timestamp'] = pd.to_datetime(self.df['Timestamp'])
        return self

    def detect_anomalies(self):
        """Flags pressure readings that deviate from their rolling baseline.

        A rolling mean/std (window = self.rolling_window) is used instead
        of one fixed mean/std for the whole series, because pump operating
        conditions drift slowly over time — a rolling baseline adapts to
        that drift instead of flagging normal variation as anomalous. Also
        computes a rolling rate-of-change on pressure to catch a sustained
        downward trend before it fully deviates (an early-warning signal,
        not just a post-hoc flag).

        Returns:
            self.
        """
        df = self.df
        rolling_mean = df['Pressure_bar'].rolling(self.rolling_window).mean()
        rolling_std = df['Pressure_bar'].rolling(self.rolling_window).std()
        df['Anomaly'] = abs(df['Pressure_bar'] - rolling_mean) > (self.anomaly_z * rolling_std)
        df['Anomaly'] = df['Anomaly'].fillna(False)

        df['Pressure_RateOfChange'] = df['Pressure_bar'].diff().rolling(20).mean()
        df['EarlyWarning'] = df['Pressure_RateOfChange'] < -0.15
        return self

    def calculate_health_index(self):
        """Combines Pressure, Flow and Temperature into one health score.

        Each variable is converted to a Z-score (how many standard
        deviations it sits from its own overall mean), then the three
        Z-scores are averaged into a single Composite_Health value. One
        combined number is more useful for a status report than three
        separate raw sensor charts, since it reflects overall equipment
        state at a glance. Composite_Health above
        self.health_alert_threshold is flagged as a System_Alert.

        Returns:
            self.
        """
        df = self.df
        z_pressure = (df['Pressure_bar'] - df['Pressure_bar'].mean()) / df['Pressure_bar'].std()
        z_flow = (df['Flow_m3h'] - df['Flow_m3h'].mean()) / df['Flow_m3h'].std()
        z_temp = (df['Temperature_C'] - df['Temperature_C'].mean()) / df['Temperature_C'].std()

        df['Composite_Health'] = (z_pressure.abs() + z_flow.abs() + z_temp.abs()) / 3
        df['System_Alert'] = df['Composite_Health'] > self.health_alert_threshold
        return self

    def _hypothesize_root_cause(self, pressure_drop, temp_rise, flow_erratic):
        """Applies a simple rule-of-thumb to suggest a likely failure mode.

        This is a simplified heuristic for demonstration, not a validated
        diagnostic model — it distinguishes three plausible subsea pump
        failure signatures by which combination of Pressure, Temperature
        and Flow behaviour they typically show.

        Args:
            pressure_drop: True if mean pressure during the event dropped
                meaningfully below the overall baseline.
            temp_rise: True if mean temperature during the event rose
                meaningfully above the overall baseline.
            flow_erratic: True if flow variability during the event was
                notably higher than its baseline variability.

        Returns:
            A short text hypothesis for the likely root cause.
        """
        if pressure_drop and temp_rise:
            return "Suspected Impeller Wear / Recirculation"
        elif pressure_drop and not temp_rise:
            return "Suspected Suction Valve Throttling or Leak"
        elif flow_erratic and not pressure_drop:
            return "Suspected Multiphase Flow Meter Error or Slugging"
        else:
            return "Undetermined - Review Manually"

    def generate_rca_report(self):
        """Groups anomaly readings into events and hypothesizes a cause for each.

        Consecutive anomalous readings are grouped into single "events"
        rather than reported individually, because an engineer reviewing a
        monthly report cares about how many distinct degradation episodes
        occurred and how severe each was — not a raw list of hundreds of
        flagged timestamps. Each event's average Pressure/Flow/Temperature
        is compared against the dataset's overall baseline to hypothesize
        a likely root cause.

        Returns:
            self. Also writes rca_report.csv to disk.
        """
        df = self.df
        baseline_pressure = df['Pressure_bar'].mean()
        baseline_temp = df['Temperature_C'].mean()
        baseline_flow_std = df['Flow_m3h'].std()

        df['Event_Group'] = (df['Anomaly'] != df['Anomaly'].shift()).cumsum()
        anomaly_rows = df[df['Anomaly']]

        records = []
        for _, group in anomaly_rows.groupby('Event_Group'):
            pressure_drop = (baseline_pressure - group['Pressure_bar'].mean()) > 3
            temp_rise = (group['Temperature_C'].mean() - baseline_temp) > 1
            flow_erratic = group['Flow_m3h'].std() > (baseline_flow_std * 1.5)

            records.append({
                'Start': group['Timestamp'].iloc[0],
                'End': group['Timestamp'].iloc[-1],
                'Duration_readings': len(group),
                'Max_Deviation_bar': round(group['Pressure_bar'].min() - baseline_pressure, 2),
                'Root_Cause_Hypothesis': self._hypothesize_root_cause(pressure_drop, temp_rise, flow_erratic),
            })

        self.events = pd.DataFrame(records)
        self.events.to_csv('rca_report.csv', index=False)
        return self

    def create_dashboard(self, filename='pump_dashboard.png'):
        """Builds and saves a 4-panel monitoring dashboard.

        Panel 1 shades each detected event's real time span directly from
        the events table (rather than a hardcoded date range), so the
        chart stays correct even if the anomaly-detection parameters
        change. Panel 4 (Composite Health) gives an at-a-glance view
        matching the alert threshold used in calculate_health_index().

        Args:
            filename: Output path for the saved dashboard image.

        Returns:
            self.
        """
        df = self.df
        fig, (ax1, ax2, ax3, ax4) = plt.subplots(4, 1, figsize=(12, 14))

        # Plot 1: Pressure over time, with dynamically detected degradation zones
        ax1.plot(df['Timestamp'], df['Pressure_bar'], 'b-', linewidth=0.8, label='Pressure')
        for i, row in self.events.iterrows():
            ax1.axvspan(row['Start'], row['End'], alpha=0.2, color='orange',
                        label='Degradation Zone' if i == 0 else None)
        ax1.scatter(df[df['Anomaly']]['Timestamp'], df[df['Anomaly']]['Pressure_bar'],
                    color='red', s=25, label='Performance Deviation')
        ax1.set_ylabel('Pressure (bar)')
        ax1.set_title('Subsea Pump — Real-Time Pressure Monitoring (Rolling Anomaly)')
        ax1.legend()
        ax1.grid(True, alpha=0.3)

        # Plot 2: Rate of change — early degradation signal
        ax2.plot(df['Timestamp'], df['Pressure_RateOfChange'], 'g-', linewidth=0.9, label='Rate of Change')
        ax2.axhline(0, color='grey', linewidth=0.6)
        ax2.scatter(df[df['EarlyWarning']]['Timestamp'], df[df['EarlyWarning']]['Pressure_RateOfChange'],
                    color='orange', s=15, label='Early Warning')
        ax2.set_ylabel('bar / reading')
        ax2.set_title('Pressure Rate of Change (Early Degradation Signal)')
        ax2.legend()
        ax2.grid(True, alpha=0.3)

        # Plot 3: Flow-Pressure-Temperature (PVT view)
        sc = ax3.scatter(df['Flow_m3h'], df['Pressure_bar'], c=df['Temperature_C'],
                          cmap='coolwarm', alpha=0.6, s=20)
        plt.colorbar(sc, ax=ax3, label='Temperature (\u00b0C)')
        ax3.set_xlabel('Flow (m\u00b3/h)')
        ax3.set_ylabel('Pressure (bar)')
        ax3.set_title('Flow\u2013Pressure\u2013Temperature Relationship (PVT View)')
        ax3.grid(True, alpha=0.3)

        # Plot 4: Composite Health Index
        ax4.plot(df['Timestamp'], df['Composite_Health'], color='purple', linewidth=0.9, label='Composite Health')
        ax4.axhline(self.health_alert_threshold, color='red', linestyle='--', linewidth=1,
                    label=f'Alert Threshold ({self.health_alert_threshold})')
        ax4.set_ylabel('Composite Health Score')
        ax4.set_xlabel('Timestamp')
        ax4.set_title('Composite Health Index (Pressure + Flow + Temperature)')
        ax4.legend()
        ax4.grid(True, alpha=0.3)

        plt.tight_layout()
        plt.savefig(filename, dpi=150)
        plt.show()
        return self

    def run_pipeline(self, filepath='pump_data.csv'):
        """Runs the full pipeline in order: load, analyze, report, visualize.

        Args:
            filepath: Path to the input CSV produced by create_data.py.

        Returns:
            self, with self.df and self.events populated.
        """
        (self.load_data(filepath)
             .detect_anomalies()
             .calculate_health_index()
             .generate_rca_report()
             .create_dashboard())
        print(f"Pipeline complete. {len(self.events)} events detected — see rca_report.csv")
        print(self.events)
        return self


if __name__ == "__main__":
    monitor = SubseaMonitor()
    monitor.run_pipeline('pump_data.csv')

import pandas as pd
import matplotlib.pyplot as plt

RECOMMENDED_ACTIONS = {
    "Suspected Impeller Wear / Recirculation": "Inspect impeller and internal clearances; verify recirculation valve function.",
    "Suspected Suction Valve Throttling or Leak": "Inspect suction valve position and seals; check for partial blockage.",
    "Suspected Multiphase Flow Meter Error or Slugging": "Check flow meter calibration; review upstream flow conditions for slugging.",
    "Undetermined - Review Manually": "Manually review raw sensor data and cross-check against maintenance logs.",
}


def load_data(filepath='pump_data.csv', rolling_window=50, anomaly_z=2.5):
    """Loads sensor data and re-runs the same anomaly flagging used in analyze_data.py.

    Kept standalone (no import from analyze_data.py) so this script can be
    run and understood on its own. The rolling window and threshold match
    analyze_data.py's detect_anomalies() so both scripts agree on what
    counts as anomalous.

    Args:
        filepath: Path to the CSV produced by create_data.py.
        rolling_window: Rolling baseline window, in readings.
        anomaly_z: Anomaly threshold, in rolling standard deviations.

    Returns:
        The sensor DataFrame with an added boolean 'Anomaly' column.
    """
    df = pd.read_csv(filepath)
    df['Timestamp'] = pd.to_datetime(df['Timestamp'])

    rolling_mean = df['Pressure_bar'].rolling(rolling_window).mean()
    rolling_std = df['Pressure_bar'].rolling(rolling_window).std()
    df['Anomaly'] = abs(df['Pressure_bar'] - rolling_mean) > (anomaly_z * rolling_std)
    df['Anomaly'] = df['Anomaly'].fillna(False)
    return df


def find_worst_cluster(df, cluster_window=100, padding_readings=100):
    """Finds the time period with the densest cluster of flagged anomalies.

    A slow drift often produces several short, separate anomaly flags
    close together in time rather than one continuous flagged block,
    because a rolling baseline partially adapts as pressure drifts.
    Treating nearby flags as one underlying incident is a more realistic
    read on operational impact than picking whichever single reading has
    the largest raw deviation, which tends to surface a brief noise spike.

    Caveat: on noisy synthetic data, ordinary randomness can occasionally
    produce a tighter false-positive cluster than the real degradation
    elsewhere in the series. If the picked incident looks wrong against
    the full dashboard, use select_window_by_date() instead with a range
    chosen by eye from the Composite Health panel.

    Args:
        df: Sensor DataFrame with an 'Anomaly' boolean column (see load_data).
        cluster_window: Rolling window (in readings) used to count how many
            anomalies fall near each point in time.
        padding_readings: Extra readings included before/after the incident
            span, so the resulting plot has context rather than being
            cropped tight to just the flagged points.

    Returns:
        Tuple of (window, incident, flagged): the padded DataFrame slice to
        plot, the full contiguous span covering the cluster (used for
        summary stats), and just the readings that were flagged anomalous
        within it (used as scatter markers).
    """
    density = df['Anomaly'].rolling(cluster_window, center=True, min_periods=1).sum()
    peak_idx = density.idxmax()

    lower = max(0, peak_idx - cluster_window)
    upper = min(len(df) - 1, peak_idx + cluster_window)
    nearby = df.iloc[lower:upper]
    flagged = nearby[nearby['Anomaly']]
    if flagged.empty:
        flagged = df.iloc[[peak_idx]]

    start_idx, end_idx = flagged.index.min(), flagged.index.max()
    incident = df.iloc[start_idx:end_idx + 1]
    window = df.iloc[max(0, start_idx - padding_readings): end_idx + padding_readings]
    return window, incident, flagged


def select_window_by_date(df, start, end, padding_readings=100):
    """Builds a case-study window around a manually chosen date range.

    Automatic cluster-picking (find_worst_cluster) is a convenience
    default, but it can be misled by ordinary noise producing a tighter
    false-positive cluster than the real, slower degradation elsewhere in
    the data. In practice an engineer reviewing the full dashboard
    (particularly the Composite Health panel) would spot the real incident
    by eye and zoom into it directly — pass in the start/end identified
    that way.

    Args:
        df: Sensor DataFrame with an 'Anomaly' boolean column (see load_data).
        start: Start of the incident, e.g. '2026-01-05'.
        end: End of the incident, e.g. '2026-01-06 18:00:00'.
        padding_readings: Extra readings included before/after the chosen
            range for context in the resulting plot.

    Returns:
        Tuple of (window, incident, flagged), matching find_worst_cluster's
        return shape.
    """
    start, end = pd.Timestamp(start), pd.Timestamp(end)
    incident = df[(df['Timestamp'] >= start) & (df['Timestamp'] <= end)]
    flagged = incident[incident['Anomaly']]

    start_idx, end_idx = incident.index.min(), incident.index.max()
    window = df.iloc[max(0, start_idx - padding_readings): end_idx + padding_readings]
    return window, incident, flagged


def hypothesize_root_cause(df, incident):
    """Compares the incident's average readings to the dataset baseline to suggest a cause.

    Same simplified rule-of-thumb used in analyze_data.py's
    generate_rca_report(): pressure down + temperature up looks different
    from pressure down + temperature flat, and each combination points to
    a different plausible failure mode. Uses the full incident window's
    average, not just the sparse flagged readings within it, since a few
    scattered flags can straddle both the dip and the recovery bounce and
    average out to nothing. This is illustrative, not a validated
    diagnostic model.

    Args:
        df: Full sensor DataFrame, used to compute the overall baseline.
        incident: The full contiguous span of readings that make up the
            incident (not just the flagged subset).

    Returns:
        A short text hypothesis for the likely root cause.
    """
    pressure_drop = (df['Pressure_bar'].mean() - incident['Pressure_bar'].mean()) > 3
    temp_rise = (incident['Temperature_C'].mean() - df['Temperature_C'].mean()) > 1
    flow_erratic = incident['Flow_m3h'].std() > (df['Flow_m3h'].std() * 1.5)

    if pressure_drop and temp_rise:
        return "Suspected Impeller Wear / Recirculation"
    elif pressure_drop and not temp_rise:
        return "Suspected Suction Valve Throttling or Leak"
    elif flow_erratic and not pressure_drop:
        return "Suspected Multiphase Flow Meter Error or Slugging"
    else:
        return "Undetermined - Review Manually"


def build_case_study(df, window, incident, flagged, filename='event_case_study.png'):
    """Builds a zoomed, annotated figure around a single detected incident.

    Rather than showing the full 10-day monitoring window (which
    compresses one incident into an unreadable sliver), this zooms into
    the incident plus padding before/after, so pressure, flow and
    temperature behaviour around it is actually legible — the same reason
    a geoscientist zooms into a zone of interest rather than presenting a
    full, congested section.

    Args:
        df: Full sensor DataFrame, used to compute the baseline shown in
            the summary box.
        window: The padded DataFrame slice to plot.
        incident: The full contiguous span of readings that make up the
            incident, used for the shaded region and summary statistics.
        flagged: The subset of incident readings that tripped the anomaly
            detector, shown as scatter markers.
        filename: Output path for the saved case-study image.

    Returns:
        None. Saves and displays the figure.
    """
    event_start, event_end = incident['Timestamp'].min(), incident['Timestamp'].max()
    root_cause = hypothesize_root_cause(df, incident)
    max_deviation = round(incident['Pressure_bar'].min() - df['Pressure_bar'].mean(), 2)

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(11, 8.5), sharex=True)
    fig.subplots_adjust(bottom=0.24)

    ax1.plot(window['Timestamp'], window['Pressure_bar'], color='tab:blue', label='Pressure (bar)')
    ax1.axvspan(event_start, event_end, color='orange', alpha=0.25, label='Detected Incident')
    ax1.scatter(flagged['Timestamp'], flagged['Pressure_bar'], color='red', s=25, label='Flagged Reading', zorder=5)
    ax1.set_ylabel('Pressure (bar)')
    ax1.set_title(f"Case Study: Incident around {event_start}")
    ax1.legend(loc='upper right')
    ax1.grid(True, alpha=0.3)

    ax2b = ax2.twinx()
    l1, = ax2.plot(window['Timestamp'], window['Flow_m3h'], color='tab:green', label='Flow (m3/h)')
    l2, = ax2b.plot(window['Timestamp'], window['Temperature_C'], color='tab:red', label='Temperature (C)')
    ax2.axvspan(event_start, event_end, color='orange', alpha=0.25)
    ax2.set_ylabel('Flow (m\u00b3/h)', color='tab:green')
    ax2b.set_ylabel('Temperature (\u00b0C)', color='tab:red')
    ax2.set_xlabel('Timestamp')
    ax2.grid(True, alpha=0.3)
    ax2.legend(handles=[l1, l2], loc='upper right')

    action = RECOMMENDED_ACTIONS.get(root_cause, "Manual review recommended.")
    summary = (
        f"Incident duration: {len(incident)} readings   |   Max deviation: {max_deviation} bar\n"
        f"Root cause hypothesis: {root_cause}\n"
        f"Recommended action: {action}"
    )
    fig.text(0.5, 0.06, summary, fontsize=10, va='center', ha='center',
              bbox=dict(boxstyle='round', facecolor='#f2f2f2', edgecolor='grey'))

    plt.savefig(filename, dpi=150)
    plt.show()


if __name__ == "__main__":
    sensor_df = load_data()

    # Option A — automatic: picks the densest cluster of flagged readings.
    # Can be misled by noise (see caveat in find_worst_cluster's docstring).
    # plot_window, event_incident, event_flagged = find_worst_cluster(sensor_df)

    # Option B — manual (recommended): zoom into a date range identified by
    # eye from the full dashboard (e.g. where Composite Health stays above
    # threshold the longest). Edit these dates to match what you see.
    plot_window, event_incident, event_flagged = select_window_by_date(
        sensor_df, '2026-01-05', '2026-01-06 18:00:00'
    )

    build_case_study(sensor_df, plot_window, event_incident, event_flagged)
    print(f"Case study built around {event_incident['Timestamp'].min()} \u2013 {event_incident['Timestamp'].max()}")
    print("Root cause hypothesis:", hypothesize_root_cause(sensor_df, event_incident))